services:
  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./conf:/usr/local/etc/redis
    command:
      [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    restart: unless-stopped