version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2023-04-20T17-56-55Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: Minio123456
    command: server /data --console-address ":9090"