version: '3'
services:
  mysql_1:
    image: mysql:8
    container_name: mysql_a
    environment:
      - MYSQL_ROOT_PASSWORD=mysql123456
    ports:
      - 13306:3306
  mysql_2:
    image: mysql:8
    container_name: mysql_b
    environment:
      - MYSQL_ROOT_PASSWORD=mysql123456
    ports:
      - 13307:3306