version: '3.8'

services:
  static-resource-server:
    image: nginx:1.26.1
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
      - "./data:/usr/share/nginx/html"
    restart: always
