version: '3'
services:
  postgres_14:
    container_name: postgres_14
    image: postgres:14.10
    environment:
      - POSTGRES_PASSWORD=Pg@123456
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres-14.2/data:/var/lib/postgresql/data
    restart: always