version: '3'
services:
  mysql_8:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql@123456
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - ./data:/var/lib/mysql