version: '3'
services:
  redis-c-7000:
    container_name: redis-c-7000
    image: redis:7.0-rc2
    ports:
      - 7000:7000
      - 17000:17000
    volumes:
      - ./7000/conf:/usr/local/etc/redis
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
  redis-c-7001:
    container_name: redis-c-7001
    image: redis:7.0-rc2
    ports:
      - 7001:7001
      - 17001:17001
    volumes:
      - ./7001/conf:/usr/local/etc/redis
    command:
      [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  redis-c-7002:
    container_name: redis-c-7002
    image: redis:7.0-rc2
    ports:
      - 7002:7002
      - 17002:17002
    volumes:
      - ./7002/conf:/usr/local/etc/redis
    command:
      [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  redis-c-7003:
    container_name: redis-c-7003
    image: redis:7.0-rc2
    ports:
      - 7003:7003
      - 17003:17003
    volumes:
      - ./7003/conf:/usr/local/etc/redis
    command:
      [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  redis-c-7004:
    container_name: redis-c-7004
    image: redis:7.0-rc2
    ports:
      - 7004:7004
      - 17004:17004
    volumes:
      - ./7004/conf:/usr/local/etc/redis
    command:
      [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  redis-c-7005:
    container_name: redis-c-7005
    image: redis:7.0-rc2
    ports:
      - 7005:7005
      - 17005:17005
    volumes:
      - ./7005/conf:/usr/local/etc/redis
    command:
      [ "redis-server", "/usr/local/etc/redis/redis.conf" ]